apiVersion: v1
kind: Pod
metadata:
  name: mysql-app
  labels:
    name: mysql-app
spec:
  containers:
  - name: mysql-app
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "1234"
    ports:
    - containerPort: 3306
